### ISSUE TITLE
the paper corresponding to this code

### ISSUE THREAD

**Issue by SuperLuckyStar666** [GiacomoPracucci/RL-edge-computing#1]
Hi author, where can I view the paper corresponding to this code?

**Comment by GiacomoPracucci** [comment]
Hi!

An article was written about the work only recently and I did not deal with it personally. I know it was pending publication but I don't know if it has been published yet. The title of the paper is "Comparing Actor-Critic and Neuroevolution Approaches for Traffic Offloading in FaaS-powered Edge Systems," you can find references to it in the fork of this repo. 

No major changes have been developed, so you can use that article as a reference for the code you find in this repo.

If you know Italian, I can send you the thesis paper. 

At your disposal
